mod camera;
mod constants;
pub mod common;
mod pacman;
mod score;
mod ghosts;
mod tunnels;
mod random;
mod lives;
mod level;
mod speed;
pub mod map;
mod walls;
mod ghost_house;
mod ghost_corners;
mod ghost_house_gate;
mod animation;
mod helper;
mod spritesheet;
mod life_cycle;
mod ready_screen;
mod game_over_screen;
mod edibles;
mod interactions;
mod game_assets;